# Adat bővítés

In [1]:
import pandas as pd
import math
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.dates import YearLocator, MonthLocator, DateFormatter
from datetime import datetime 
import numpy as np

In [16]:
data = pd.read_csv('database_2017_03.csv')
wheater = pd.read_csv('weather_info.csv')
database = pd.merge(data, wheater, on='date')
database['date'] = pd.to_datetime(database['date'])
database['day_of_week'] = np.nan
print(len(database))
for i in range(0, len(database)):
    database.set_value(i, 'day_of_week', database.loc[i]['date'].weekday())
    database.set_value(i, 'tick', database.loc[i]['tick'].split('-')[0])
    if ((i % 1000) == 0):
        print(i)
# database

10944
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000

In [17]:
database = database.dropna()
database['holiday'] = 0
database['workday'] = 0

database.loc[(database['day_of_week'] == 1), 'workday'] = 1
database.loc[(database['day_of_week'] == 2), 'workday'] = 1
database.loc[(database['day_of_week'] == 3), 'workday'] = 1
database.loc[(database['day_of_week'] == 4), 'workday'] = 1
database.loc[(database['day_of_week'] == 5), 'workday'] = 1

database.loc[(database['date'] == '2016-01-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-15'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-27'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-28'), 'holiday'] = 1
database.loc[(database['date'] == '2016-05-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-05-15'), 'holiday'] = 1
database.loc[(database['date'] == '2016-08-20'), 'holiday'] = 1
database.loc[(database['date'] == '2016-10-23'), 'holiday'] = 1
database.loc[(database['date'] == '2016-11-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-12-25'), 'holiday'] = 1
database.loc[(database['date'] == '2016-12-26'), 'holiday'] = 1
database.loc[(database['date'] == '2016-01-01') | \
             (database['date'] == '2016-03-15') | \
             (database['date'] == '2016-03-27') | \
             (database['date'] == '2016-03-28') | \
             (database['date'] == '2016-05-01') | \
             (database['date'] == '2016-05-15') | \
             (database['date'] == '2016-08-20') | \
             (database['date'] == '2016-10-23') | \
             (database['date'] == '2016-11-01') | \
             (database['date'] == '2016-12-25') | \
             (database['date'] == '2016-12-26'), 'workday'] = 0

database.loc[(database['date'] == '2017-01-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-03-15'), 'holiday'] = 1
database.loc[(database['date'] == '2017-04-16'), 'holiday'] = 1
database.loc[(database['date'] == '2017-04-17'), 'holiday'] = 1
database.loc[(database['date'] == '2017-05-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-06-04'), 'holiday'] = 1
database.loc[(database['date'] == '2017-08-20'), 'holiday'] = 1
database.loc[(database['date'] == '2017-10-23'), 'holiday'] = 1
database.loc[(database['date'] == '2017-11-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-12-25'), 'holiday'] = 1
database.loc[(database['date'] == '2017-12-26'), 'holiday'] = 1
database.loc[(database['date'] == '2017-01-01') | \
             (database['date'] == '2017-03-15') | \
             (database['date'] == '2017-04-16') | \
             (database['date'] == '2017-04-17') | \
             (database['date'] == '2017-05-01') | \
             (database['date'] == '2017-06-04') | \
             (database['date'] == '2017-08-20') | \
             (database['date'] == '2017-10-23') | \
             (database['date'] == '2017-11-01') | \
             (database['date'] == '2017-12-25') | \
             (database['date'] == '2017-12-26'), 'workday'] = 0

database.to_csv('Data_Expansion.csv', sep=',', index=False)
database

,date,tick,export,import,system_load,max,min,rain,snow,avg_max,avg_min,day_of_week,holiday,workday
0,2016-01-01,0,1503.0,2351.0,4071.0,-3,-10,0,0.0,2,-2,4.0,1,0
1,2016-01-01,1,1613.0,2282.0,3873.0,-3,-10,0,0.0,2,-2,4.0,1,0
2,2016-01-01,2,1779.0,2224.0,3581.0,-3,-10,0,0.0,2,-2,4.0,1,0
3,2016-01-01,3,1923.0,2160.0,3356.0,-3,-10,0,0.0,2,-2,4.0,1,0
4,2016-01-01,4,1922.0,2115.0,3294.0,-3,-10,0,0.0,2,-2,4.0,1,0
5,2016-01-01,5,1843.0,2037.0,3302.0,-3,-10,0,0.0,2,-2,4.0,1,0
6,2016-01-01,6,1847.0,2067.0,3375.0,-3,-10,0,0.0,2,-2,4.0,1,0
7,2016-01-01,7,1835.0,2126.0,3436.0,-3,-10,0,0.0,2,-2,4.0,1,0
8,2016-01-01,8,1735.0,2165.0,3565.0,-3,-10,0,0.0,2,-2,4.0,1,0
9,2016-01-01,9,1516.0,2098.0,3755.0,-3,-10,0,0.0,2,-2,4.0,1,0
10,2016-01-01,10,1380.0,2115.0,3916.0,-3,-10,0,0.0,2,-2,4.0,1,0
11,2016-01-01,11,1244.0,2101.0,4058.0,-3,-10,0,0.0,2,-2,4.0,1,0
12,2016-01-01,12,1135.0,2033.0,4132.0,-3,-10,0,0.0,2,-2,4.0,1,0
13,2016-01-01,13,1074.0,1924.0,4075.0,-3,-10,0,0.0,2,-2,4.0,1,0
14,2016-01-01,14,1170.0,2060.0,4073.0,-3,-10,0,0.0,2,-2,4.0,1,0
15,2016-01-01,15,1254.0,2202.0,4129.0,-3,-10,0,0.0,2,-2,4.0,1,0
16,2016-01-01,16,936.0,2212.0,4404.0,-3,-10,0,0.0,2,-2,4.0,1,0
17,2016-01-01,17,993.0,2295.0,4523.0,-3,-10,0,0.0,2,-2,4.0,1,0
18,2016-01-01,18,1101.0,2365.0,4497.0,-3,-10,0,0.0,2,-2,4.0,1,0
19,2016-01-01,19,1137.0,2360.0,4468.0,-3,-10,0,0.0,2,-2,4.0,1,0
20,2016-01-01,20,1258.0,2388.0,4372.0,-3,-10,0,0.0,2,-2,4.0,1,0
21,2016-01-01,21,1347.0,2417.0,4267.0,-3,-10,0,0.0,2,-2,4.0,1,0
22,2016-01-01,22,1571.0,2450.0,4089.0,-3,-10,0,0.0,2,-2,4.0,1,0
23,2016-01-01,23,1646.0,2333.0,3879.0,-3,-10,0,0.0,2,-2,4.0,1,0
24,2016-01-02,0,1708.0,2195.0,3612.0,-5,-8,0,0.5,2,-2,5.0,0,1
25,2016-01-02,1,1842.0,2183.0,3475.0,-5,-8,0,0.5,2,-2,5.0,0,1
26,2016-01-02,2,1858.0,2048.0,3327.0,-5,-8,0,0.5,2,-2,5.0,0,1
27,2016-01-02,3,1808.0,1921.0,3230.0,-5,-8,0,0.5,2,-2,5.0,0,1
28,2016-01-02,4,1695.0,1863.0,3278.0,-5,-8,0,0.5,2,-2,5.0,0,1
29,2016-01-02,5,1636.0,1948.0,3428.0,-5,-8,0,0.5,2,-2,5.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10914,2017-03-30,18,662.0,2555.0,4958.0,20,9,0,0.0,13,4,3.0,0,1
10915,2017-03-30,19,607.0,2817.0,5257.0,20,9,0,0.0,13,4,3.0,0,1
10916,2017-03-30,20,580.0,2782.0,5305.0,20,9,0,0.0,13,4,3.0,0,1
10917,2017-03-30,21,857.0,2702.0,4974.0,20,9,0,0.0,13,4,3.0,0,1
10918,2017-03-30,22,1105.0,2688.0,4670.0,20,9,0,0.0,13,4,3.0,0,1
10919,2017-03-30,23,1194.0,2685.0,4519.0,20,9,0,0.0,13,4,3.0,0,1
10920,2017-03-31,0,1221.0,2495.0,4274.0,20,6,0,0.0,13,4,4.0,0,1
10921,2017-03-31,1,1184.0,2272.0,4083.0,20,6,0,0.0,13,4,4.0,0,1
10922,2017-03-31,2,1111.0,2000.0,3869.0,20,6,0,0.0,13,4,4.0,0,1
10923,2017-03-31,3,963.0,1832.0,3816.0,20,6,0,0.0,13,4,4.0,0,1
10924,2017-03-31,4,973.0,1918.0,3898.0,20,6,0,0.0,13,4,4.0,0,1
10925,2017-03-31,5,900.0,2154.0,4242.0,20,6,0,0.0,13,4,4.0,0,1
10926,2017-03-31,6,584.0,2392.0,4871.0,20,6,0,0.0,13,4,4.0,0,1
10927,2017-03-31,7,446.0,2474.0,5172.0,20,6,0,0.0,13,4,4.0,0,1
10928,2017-03-31,8,396.0,2357.0,5122.0,20,6,0,0.0,13,4,4.0,0,1
10929,2017-03-31,9,437.0,2396.0,5101.0,20,6,0,0.0,13,4,4.0,0,1
10930,2017-03-31,10,633.0,2586.0,5081.0,20,6,0,0.0,13,4,4.0,0,1
10931,2017-03-31,11,833.0,2727.0,5063.0,20,6,0,0.0,13,4,4.0,0,1
10932,2017-03-31,12,1012.0,2786.0,5049.0,20,6,0,0.0,13,4,4.0,0,1
10933,2017-03-31,13,1187.0,2855.0,4975.0,20,6,0,0.0,13,4,4.0,0,1
10934,2017-03-31,14,1184.0,3031.0,4968.0,20,6,0,0.0,13,4,4.0,0,1
10935,2017-03-31,15,1154.0,3003.0,4994.0,20,6,0,0.0,13,4,4.0,0,1
10936,2017-03-31,16,1079.0,2912.0,4983.0,20,6,0,0.0,13,4,4.0,0,1
10937,2017-03-31,17,1033.0,2802.0,4891.0,20,6,0,0.0,13,4,4.0,0,1
10938,2017-03-31,18,887.0,2648.0,4849.0,20,6,0,0.0,13,4,4.0,0,1
10939,2017-03-31,19,742.0,2740.0,5106.0,20,6,0,0.0,13,4,4.0,0,1
10940,2017-03-31,20,811.0,2779.0,5169.0,20,6,0,0.0,13,4,4.0,0,1
10941,2017-03-31,21,1092.0,2752.0,4888.0,20,6,0,0.0,13,4,4.0,0,1
10942,2017-03-31,22,1352.0,2697.0,4590.0,20,6,0,0.0,13,4,4.0,0,1
10943,2017-03-31,23,1450.0,2635.0,4453.0,20,6,0,0.0,13,4,4.0,0,1

In [ ]:
#