# Adat bővítés

In [6]:
import pandas as pd
import math
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.dates import YearLocator, MonthLocator, DateFormatter
from datetime import datetime 
import numpy as np

In [7]:
data = pd.read_csv('database_2017_03.csv')
wheater = pd.read_csv('weather_info.csv')
database = pd.merge(data, wheater, on='date')
database['date'] = pd.to_datetime(database['date'])
database['day_of_week'] = np.nan
print(len(database))
for i in range(0, len(database)):
    database.set_value(i, 'day_of_week', database.loc[i]['date'].weekday())
    database.set_value(i, 'tick', database.loc[i]['tick'].split('-')[0])
#     if ((i % 1000) == 0):
#         print(i)
# database

10944
0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000

In [8]:
database = database.dropna()
database['holiday'] = 0
database['workday'] = 0

database.loc[(database['day_of_week'] == 1), 'workday'] = 1
database.loc[(database['day_of_week'] == 2), 'workday'] = 1
database.loc[(database['day_of_week'] == 3), 'workday'] = 1
database.loc[(database['day_of_week'] == 4), 'workday'] = 1
database.loc[(database['day_of_week'] == 5), 'workday'] = 1

database.loc[(database['date'] == '2016-01-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-15'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-27'), 'holiday'] = 1
database.loc[(database['date'] == '2016-03-28'), 'holiday'] = 1
database.loc[(database['date'] == '2016-05-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-05-15'), 'holiday'] = 1
database.loc[(database['date'] == '2016-08-20'), 'holiday'] = 1
database.loc[(database['date'] == '2016-10-23'), 'holiday'] = 1
database.loc[(database['date'] == '2016-11-01'), 'holiday'] = 1
database.loc[(database['date'] == '2016-12-25'), 'holiday'] = 1
database.loc[(database['date'] == '2016-12-26'), 'holiday'] = 1
database.loc[(database['date'] == '2016-01-01') | \
             (database['date'] == '2016-03-15') | \
             (database['date'] == '2016-03-27') | \
             (database['date'] == '2016-03-28') | \
             (database['date'] == '2016-05-01') | \
             (database['date'] == '2016-05-15') | \
             (database['date'] == '2016-08-20') | \
             (database['date'] == '2016-10-23') | \
             (database['date'] == '2016-11-01') | \
             (database['date'] == '2016-12-25') | \
             (database['date'] == '2016-12-26'), 'workday'] = 0

database.loc[(database['date'] == '2017-01-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-03-15'), 'holiday'] = 1
database.loc[(database['date'] == '2017-04-16'), 'holiday'] = 1
database.loc[(database['date'] == '2017-04-17'), 'holiday'] = 1
database.loc[(database['date'] == '2017-05-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-06-04'), 'holiday'] = 1
database.loc[(database['date'] == '2017-08-20'), 'holiday'] = 1
database.loc[(database['date'] == '2017-10-23'), 'holiday'] = 1
database.loc[(database['date'] == '2017-11-01'), 'holiday'] = 1
database.loc[(database['date'] == '2017-12-25'), 'holiday'] = 1
database.loc[(database['date'] == '2017-12-26'), 'holiday'] = 1
database.loc[(database['date'] == '2017-01-01') | \
             (database['date'] == '2017-03-15') | \
             (database['date'] == '2017-04-16') | \
             (database['date'] == '2017-04-17') | \
             (database['date'] == '2017-05-01') | \
             (database['date'] == '2017-06-04') | \
             (database['date'] == '2017-08-20') | \
             (database['date'] == '2017-10-23') | \
             (database['date'] == '2017-11-01') | \
             (database['date'] == '2017-12-25') | \
             (database['date'] == '2017-12-26'), 'workday'] = 0

database.to_csv('Data_Expansion.csv', sep=',', index=False)
database

,date,tick,export,import,system_load,max,min,rain,snow,avg_max,avg_min,day_of_week,holiday,workday
0,2016-01-01,0,1503.0,2351.0,4071.0,-3,-10,0,0.0,2,-2,4.0,1,0
1,2016-01-01,1,1613.0,2282.0,3873.0,-3,-10,0,0.0,2,-2,4.0,1,0
2,2016-01-01,2,1779.0,2224.0,3581.0,-3,-10,0,0.0,2,-2,4.0,1,0
3,2016-01-01,3,1923.0,2160.0,3356.0,-3,-10,0,0.0,2,-2,4.0,1,0
4,2016-01-01,4,1922.0,2115.0,3294.0,-3,-10,0,0.0,2,-2,4.0,1,0
5,2016-01-01,5,1843.0,2037.0,3302.0,-3,-10,0,0.0,2,-2,4.0,1,0
6,2016-01-01,6,1847.0,2067.0,3375.0,-3,-10,0,0.0,2,-2,4.0,1,0
7,2016-01-01,7,1835.0,2126.0,3436.0,-3,-10,0,0.0,2,-2,4.0,1,0
8,2016-01-01,8,1735.0,2165.0,3565.0,-3,-10,0,0.0,2,-2,4.0,1,0
9,2016-01-01,9,1516.0,2098.0,3755.0,-3,-10,0,0.0,2,-2,4.0,1,0
10,2016-01-01,10,1380.0,2115.0,3916.0,-3,-10,0,0.0,2,-2,4.0,1,0
11,2016-01-01,11,1244.0,2101.0,4058.0,-3,-10,0,0.0,2,-2,4.0,1,0
12,2016-01-01,12,1135.0,2033.0,4132.0,-3,-10,0,0.0,2,-2,4.0,1,0
13,2016-01-01,13,1074.0,1924.0,4075.0,-3,-10,0,0.0,2,-2,4.0,1,0
14,2016-01-01,14,1170.0,2060.0,4073.0,-3,-10,0,0.0,2,-2,4.0,1,0
15,2016-01-01,15,1254.0,2202.0,4129.0,-3,-10,0,0.0,2,-2,4.0,1,0
16,2016-01-01,16,936.0,2212.0,4404.0,-3,-10,0,0.0,2,-2,4.0,1,0
17,2016-01-01,17,993.0,2295.0,4523.0,-3,-10,0,0.0,2,-2,4.0,1,0
18,2016-01-01,18,1101.0,2365.0,4497.0,-3,-10,0,0.0,2,-2,4.0,1,0
19,2016-01-01,19,1137.0,2360.0,4468.0,-3,-10,0,0.0,2,-2,4.0,1,0
20,2016-01-01,20,1258.0,2388.0,4372.0,-3,-10,0,0.0,2,-2,4.0,1,0
21,2016-01-01,21,1347.0,2417.0,4267.0,-3,-10,0,0.0,2,-2,4.0,1,0
22,2016-01-01,22,1571.0,2450.0,4089.0,-3,-10,0,0.0,2,-2,4.0,1,0
23,2016-01-01,23,1646.0,2333.0,3879.0,-3,-10,0,0.0,2,-2,4.0,1,0
24,2016-01-02,0,1708.0,2195.0,3612.0,-5,-8,0,0.5,2,-2,5.0,0,1
25,2016-01-02,1,1842.0,2183.0,3475.0,-5,-8,0,0.5,2,-2,5.0,0,1
26,2016-01-02,2,1858.0,2048.0,3327.0,-5,-8,0,0.5,2,-2,5.0,0,1
27,2016-01-02,3,1808.0,1921.0,3230.0,-5,-8,0,0.5,2,-2,5.0,0,1
28,2016-01-02,4,1695.0,1863.0,3278.0,-5,-8,0,0.5,2,-2,5.0,0,1
29,2016-01-02,5,1636.0,1948.0,3428.0,-5,-8,0,0.5,2,-2,5.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10914,2017-03-30,18,662.0,2555.0,4958.0,20,9,0,0.0,13,4,3.0,0,1
10915,2017-03-30,19,607.0,2817.0,5257.0,20,9,0,0.0,13,4,3.0,0,1
10916,2017-03-30,20,580.0,2782.0,5305.0,20,9,0,0.0,13,4,3.0,0,1
10917,2017-03-30,21,857.0,2702.0,4974.0,20,9,0,0.0,13,4,3.0,0,1
10918,2017-03-30,22,1105.0,2688.0,4670.0,20,9,0,0.0,13,4,3.0,0,1
10919,2017-03-30,23,1194.0,2685.0,4519.0,20,9,0,0.0,13,4,3.0,0,1
10920,2017-03-31,0,1221.0,2495.0,4274.0,20,6,0,0.0,13,4,4.0,0,1
10921,2017-03-31,1,1184.0,2272.0,4083.0,20,6,0,0.0,13,4,4.0,0,1
10922,2017-03-31,2,1111.0,2000.0,3869.0,20,6,0,0.0,13,4,4.0,0,1
10923,2017-03-31,3,963.0,1832.0,3816.0,20,6,0,0.0,13,4,4.0,0,1
10924,2017-03-31,4,973.0,1918.0,3898.0,20,6,0,0.0,13,4,4.0,0,1
10925,2017-03-31,5,900.0,2154.0,4242.0,20,6,0,0.0,13,4,4.0,0,1
10926,2017-03-31,6,584.0,2392.0,4871.0,20,6,0,0.0,13,4,4.0,0,1
10927,2017-03-31,7,446.0,2474.0,5172.0,20,6,0,0.0,13,4,4.0,0,1
10928,2017-03-31,8,396.0,2357.0,5122.0,20,6,0,0.0,13,4,4.0,0,1
10929,2017-03-31,9,437.0,2396.0,5101.0,20,6,0,0.0,13,4,4.0,0,1
10930,2017-03-31,10,633.0,2586.0,5081.0,20,6,0,0.0,13,4,4.0,0,1
10931,2017-03-31,11,833.0,2727.0,5063.0,20,6,0,0.0,13,4,4.0,0,1
10932,2017-03-31,12,1012.0,2786.0,5049.0,20,6,0,0.0,13,4,4.0,0,1
10933,2017-03-31,13,1187.0,2855.0,4975.0,20,6,0,0.0,13,4,4.0,0,1
10934,2017-03-31,14,1184.0,3031.0,4968.0,20,6,0,0.0,13,4,4.0,0,1
10935,2017-03-31,15,1154.0,3003.0,4994.0,20,6,0,0.0,13,4,4.0,0,1
10936,2017-03-31,16,1079.0,2912.0,4983.0,20,6,0,0.0,13,4,4.0,0,1
10937,2017-03-31,17,1033.0,2802.0,4891.0,20,6,0,0.0,13,4,4.0,0,1
10938,2017-03-31,18,887.0,2648.0,4849.0,20,6,0,0.0,13,4,4.0,0,1
10939,2017-03-31,19,742.0,2740.0,5106.0,20,6,0,0.0,13,4,4.0,0,1
10940,2017-03-31,20,811.0,2779.0,5169.0,20,6,0,0.0,13,4,4.0,0,1
10941,2017-03-31,21,1092.0,2752.0,4888.0,20,6,0,0.0,13,4,4.0,0,1
10942,2017-03-31,22,1352.0,2697.0,4590.0,20,6,0,0.0,13,4,4.0,0,1
10943,2017-03-31,23,1450.0,2635.0,4453.0,20,6,0,0.0,13,4,4.0,0,1

# Homersekletenkent az atlagos rendszerterheles es szoras kiszamolasa

In [ ]:
database.__delitem__('date')
database.__delitem__('tick')
database.__delitem__('min')
database.__delitem__('rain')
database.__delitem__('snow')
database.__delitem__('avg_max')
database.__delitem__('avg_min')
database.__delitem__('day_of_week')
database.__delitem__('holiday')
database.__delitem__('workday')

In [98]:
values = pd.DataFrame()
value = []          
for i in range(database['max'].min(), database['max'].max()):
    
    value = [database[database['max']==i].sum()/database[database['max']==i].count(), \
             np.var(database[database['max']==i], 0)]
    print(value)
    values = values.append(value, ignore_index=True)

values = values.dropna()
cols = values.columns.tolist()
cols = cols[-2:] + cols[:-2]
values = values[cols]
values = values.rename(index=str, columns={'max': '˚C', 'system_load':'avg_sysload', \
                                           'export': 'avg_export', 'import': 'avg_import'})

values

[export         1219.958333
import         2259.458333
system_load    5175.000000
max              -9.000000
dtype: float64, export         122412.789931
import          32863.581597
system_load    235228.250000
max                 0.000000
dtype: float64]
[export        NaN
import        NaN
system_load   NaN
max           NaN
dtype: float64, export        NaN
import        NaN
system_load   NaN
max           NaN
dtype: float64]
[export         1379.166667
import         2709.104167
system_load    5179.833333
max              -7.000000
dtype: float64, export          68745.888889
import         212016.218316
system_load    443600.680556
max                 0.000000
dtype: float64]
[export         1105.597222
import         2985.722222
system_load    5670.055556
max              -6.000000
dtype: float64, export         170228.157215
import          49074.895062
system_load    442194.246914
max                 0.000000
dtype: float64]
[export         1347.525000
import         2464.341667
system_load    4767.166667
max              -5.000000
dtype: float64, export         162909.132708
import         169764.274931
system_load    543320.972222
max                 0.000000
dtype: float64]
[export         1060.277778
import         2448.680556
system_load    4967.277778
max              -4.000000
dtype: float64, export         293015.783951
import          31595.161844
system_load    593284.117284
max                 0.000000
dtype: float64]
[export          883.583333
import         2535.277778
system_load    5017.576389
max              -3.000000
dtype: float64, export         323522.937500
import          94387.047840
system_load    699261.063609
max                 0.000000
dtype: float64]
[export          668.398810
import         2586.886905
system_load    5249.803571
max              -2.000000
dtype: float64, export         247573.465951
import          53397.862209
system_load    472077.991178
max                 0.000000
dtype: float64]
[export          903.849359
import         2529.567308
system_load    5234.842949
max              -1.000000
dtype: float64, export         219277.102307
import         113680.501880
system_load    535700.267002
max                 0.000000
dtype: float64]
[export          795.583333
import         2322.916667
system_load    5239.145833
max               0.000000
dtype: float64, export         269690.243056
import          90249.895833
system_load    445314.124566
max                 0.000000
dtype: float64]
[export          848.220833
import         2435.325000
system_load    5394.433333
max               1.000000
dtype: float64, export         235450.280399
import          84775.744375
system_load    396553.662222
max                 0.000000
dtype: float64]
[export          788.658333
import         2465.350000
system_load    5312.529167
max               2.000000
dtype: float64, export         216878.349931
import         121315.594167
system_load    520359.990816
max                 0.000000
dtype: float64]
[export          892.932692
import         2463.775641
system_load    5097.974359
max               3.000000
dtype: float64, export         267800.710213
import         112390.571458
system_load    497452.948060
max                 0.000000
dtype: float64]
[export          668.587500
import         2191.579167
system_load    4965.670833
max               4.000000
dtype: float64, export         238210.367344
import         142768.810399
system_load    494336.512483
max                 0.000000
dtype: float64]
[export          523.416667
import         2211.053571
system_load    4861.101190
max               5.000000
dtype: float64, export         126680.743056
import         228259.003082
system_load    390218.876665
max                 0.000000
dtype: float64]
[export          648.500000
import         2436.491667
system_load    4873.016667
max               6.000000
dtype: float64, export         268324.908333
import         183796.024931
system_load    535739.133056
max                 0.000000
dtype: float64]
[export          632.375000
import         2167.799242
system_load    5063.371212
max               7.000000
dtype: float64, export         121027.249527
import          87947.205909
system_load    384769.695535
max                 0.000000
dtype: float64]
[export          472.032051
import         2234.346154
system_load    4977.282051
max               8.000000
dtype: float64, export          98614.274614
import         137283.373767
system_load    441501.337114
max                 0.000000
dtype: float64]
[export          693.481771
import         2156.674479
system_load    4858.674479
max               9.000000
dtype: float64, export         153538.515293
import         126417.922682
system_load    431191.381015
max                 0.000000
dtype: float64]
[export          546.289683
import         2121.015873
system_load    4825.847222
max              10.000000
dtype: float64, export         117876.229576
import         161686.325145
system_load    468419.490548
max                 0.000000
dtype: float64]
[export          560.628968
import         2087.769841
system_load    4765.363095
max              11.000000
dtype: float64, export         190288.542891
import         128374.244646
system_load    413567.005067
max                 0.000000
dtype: float64]
[export          674.749583
import         2085.460768
system_load    4597.884808
max              12.000000
dtype: float64, export         179152.100897
import         173354.729262
system_load    446751.013442
max                 0.000000
dtype: float64]
[export          732.433400
import         2142.425447
system_load    4622.506958
max              13.000000
dtype: float64, export         146493.772403
import         194039.166907
system_load    427976.874206
max                 0.000000
dtype: float64]
[export          653.163690
import         2201.619048
system_load    4705.422619
max              14.000000
dtype: float64, export         162914.946420
import         135532.604875
system_load    422435.035679
max                 0.000000
dtype: float64]
[export          623.744444
import         2149.272222
system_load    4672.330556
max              15.000000
dtype: float64, export         134460.901358
import         241654.459228
system_load    372774.554622
max                 0.000000
dtype: float64]
[export          605.583333
import         2025.136905
system_load    4481.125000
max              16.000000
dtype: float64, export         136294.493056
import         163047.820543
system_load    462134.859375
max                 0.000000
dtype: float64]
[export          623.583333
import         2078.525000
system_load    4609.458333
max              17.000000
dtype: float64, export         219656.909722
import         146229.766042
system_load    405815.981597
max                 0.000000
dtype: float64]
[export          618.178571
import         1869.565476
system_load    4495.148810
max              18.000000
dtype: float64, export         156709.980017
import         237804.555237
system_load    419934.424284
max                 0.000000
dtype: float64]
[export          524.833333
import         1891.201923
system_load    4419.342949
max              19.000000
dtype: float64, export         115265.074786
import         183529.276535
system_load    307780.936873
max                 0.000000
dtype: float64]
[export          656.116667
import         2118.737500
system_load    4562.416667
max              20.000000
dtype: float64, export         115883.753056
import         214751.201927
system_load    333351.801389
max                 0.000000
dtype: float64]
[export          614.208333
import         1886.009259
system_load    4356.370370
max              21.000000
dtype: float64, export         170635.590856
import         178060.351766
system_load    381918.149863
max                 0.000000
dtype: float64]
[export          503.050000
import         1980.335417
system_load    4570.600000
max              22.000000
dtype: float64, export         124491.426667
import         199151.772912
system_load    276607.027500
max                 0.000000
dtype: float64]
[export          609.076923
import         1931.073718
system_load    4466.358974
max              23.000000
dtype: float64, export         127090.045365
import         158399.125976
system_load    314056.800625
max                 0.000000
dtype: float64]
[export          527.047619
import         1965.738095
system_load    4394.880952
max              24.000000
dtype: float64, export         139204.450113
import         147763.348073
system_load    235905.009637
max                 0.000000
dtype: float64]
[export          462.397059
import         1960.426471
system_load    4405.000000
max              25.000000
dtype: float64, export         101925.734501
import         158912.774005
system_load    321317.539216
max                 0.000000
dtype: float64]
[export          488.770833
import         2038.440476
system_load    4522.958333
max              26.000000
dtype: float64, export         103202.254030
import         170906.020266
system_load    354883.819692
max                 0.000000
dtype: float64]
[export          389.563596
import         1869.642544
system_load    4474.122807
max              27.000000
dtype: float64, export          61063.447710
import         195169.045471
system_load    405894.410357
max                 0.000000
dtype: float64]
[export          551.727273
import         1911.799242
system_load    4472.227273
max              28.000000
dtype: float64, export         114310.986226
import         113444.274090
system_load    388557.357438
max                 0.000000
dtype: float64]
[export          640.544444
import         1945.791667
system_load    4457.544444
max              29.000000
dtype: float64, export         117158.986914
import         158739.614931
system_load    387410.714691
max                 0.000000
dtype: float64]
[export          809.708333
import         1862.750000
system_load    4417.100000
max              30.000000
dtype: float64, export         142633.331597
import         100548.145833
system_load    395196.548333
max                 0.000000
dtype: float64]
[export          596.083333
import         1995.656250
system_load    4655.161458
max              31.000000
dtype: float64, export          76038.118056
import         156611.767253
system_load    471549.031223
max                 0.000000
dtype: float64]
[export          605.513889
import         1993.388889
system_load    4474.625000
max              32.000000
dtype: float64, export         191077.944252
import         205863.237654
system_load    440837.651042
max                 0.000000
dtype: float64]
[export          815.625000
import         2065.791667
system_load    4832.583333
max              33.000000
dtype: float64, export         109042.734375
import         204048.581597
system_load    653193.326389
max                 0.000000
dtype: float64]
[export          450.694444
import         2154.513889
system_load    4968.208333
max              34.000000
dtype: float64, export          95812.156636
import         184269.944252
system_load    414805.831597
max                 0.000000
dtype: float64]

      avg_sysload    ˚C     avg_export     avg_import
0     5175.000000  -9.0    1219.958333    2259.458333
1   235228.250000   0.0  122412.789931   32863.581597
4     5179.833333  -7.0    1379.166667    2709.104167
5   443600.680556   0.0   68745.888889  212016.218316
6     5670.055556  -6.0    1105.597222    2985.722222
7   442194.246914   0.0  170228.157215   49074.895062
8     4767.166667  -5.0    1347.525000    2464.341667
9   543320.972222   0.0  162909.132708  169764.274931
10    4967.277778  -4.0    1060.277778    2448.680556
11  593284.117284   0.0  293015.783951   31595.161844
12    5017.576389  -3.0     883.583333    2535.277778
13  699261.063609   0.0  323522.937500   94387.047840
14    5249.803571  -2.0     668.398810    2586.886905
15  472077.991178   0.0  247573.465951   53397.862209
16    5234.842949  -1.0     903.849359    2529.567308
17  535700.267002   0.0  219277.102307  113680.501880
18    5239.145833   0.0     795.583333    2322.916667
19  445314.124566   0.0  269690.243056   90249.895833
20    5394.433333   1.0     848.220833    2435.325000
21  396553.662222   0.0  235450.280399   84775.744375
22    5312.529167   2.0     788.658333    2465.350000
23  520359.990816   0.0  216878.349931  121315.594167
24    5097.974359   3.0     892.932692    2463.775641
25  497452.948060   0.0  267800.710213  112390.571458
26    4965.670833   4.0     668.587500    2191.579167
27  494336.512483   0.0  238210.367344  142768.810399
28    4861.101190   5.0     523.416667    2211.053571
29  390218.876665   0.0  126680.743056  228259.003082
30    4873.016667   6.0     648.500000    2436.491667
31  535739.133056   0.0  268324.908333  183796.024931
..            ...   ...            ...            ...
58    4562.416667  20.0     656.116667    2118.737500
59  333351.801389   0.0  115883.753056  214751.201927
60    4356.370370  21.0     614.208333    1886.009259
61  381918.149863   0.0  170635.590856  178060.351766
62    4570.600000  22.0     503.050000    1980.335417
63  276607.027500   0.0  124491.426667  199151.772912
64    4466.358974  23.0     609.076923    1931.073718
65  314056.800625   0.0  127090.045365  158399.125976
66    4394.880952  24.0     527.047619    1965.738095
67  235905.009637   0.0  139204.450113  147763.348073
68    4405.000000  25.0     462.397059    1960.426471
69  321317.539216   0.0  101925.734501  158912.774005
70    4522.958333  26.0     488.770833    2038.440476
71  354883.819692   0.0  103202.254030  170906.020266
72    4474.122807  27.0     389.563596    1869.642544
73  405894.410357   0.0   61063.447710  195169.045471
74    4472.227273  28.0     551.727273    1911.799242
75  388557.357438   0.0  114310.986226  113444.274090
76    4457.544444  29.0     640.544444    1945.791667
77  387410.714691   0.0  117158.986914  158739.614931
78    4417.100000  30.0     809.708333    1862.750000
79  395196.548333   0.0  142633.331597  100548.145833
80    4655.161458  31.0     596.083333    1995.656250
81  471549.031223   0.0   76038.118056  156611.767253
82    4474.625000  32.0     605.513889    1993.388889
83  440837.651042   0.0  191077.944252  205863.237654
84    4832.583333  33.0     815.625000    2065.791667
85  653193.326389   0.0  109042.734375  204048.581597
86    4968.208333  34.0     450.694444    2154.513889
87  414805.831597   0.0   95812.156636  184269.944252

[86 rows x 4 columns]